version: "3.7"

services:
  app_dev:
    container_name: express-app-dev
    build:
      context: .
      dockerfile: ./Dockerfile
    command: yarn dev
    ports:
      - ${PORT}:${PORT}
    networks:
      - express-network
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    restart: unless-stopped
    env_file: ./.env
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - express-network

networks:
  express-network:
    driver: bridge

volumes:
  mysql:
